### ISSUE TITLE
Setting up HDRP

### ISSUE THREAD

**Issue by RohanMenon92** [RohanMenon92/AltControlGameJam2020#13]
Setting up HDRP stuff

**Comment by thanik** [comment]
Finished on migrating to HDRP. Some materials and textures need to be fixed (as I tried to guess textures for models' components).

Here is some reminders:
- SkyMap is moved to HDRI Sky. (settings is in post-processing Volume game object)
- You can make an object more glowing (without messing with bloom settings) by turning on Use Emission Intensity in settings of the material file. Make sure you change the emissive color to White and try changing Emission Intensity value.
- Creating a new HDRP material for our models must upgrade from old format Unity material because some textures are combined into one masked texture (in upgrading process) to be compatible with HDRP material.
